import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link nonce="c59aa59a-aaa6-400a-943e-eea6a6df1e68" rel="preload" as="font" fetchPriority="high" href="//st.ozone.ru/s3/ozon-fonts/gt-eesti-pro-display-medium.woff2" type="font/woff2" crossOrigin="anonymous" />
        <link nonce="c59aa59a-aaa6-400a-943e-eea6a6df1e68" rel="preload" as="font" fetchPriority="high" href="//st.ozone.ru/s3/ozon-fonts/gt-eesti-pro-display-medium-italic.woff2" type="font/woff2" crossOrigin="anonymous"/>
        <link nonce="c59aa59a-aaa6-400a-943e-eea6a6df1e68" rel="preload" as="font" fetchPriority="high" href="//st.ozone.ru/s3/ozon-fonts/gt-eesti-pro-display-regular.woff2" type="font/woff2" crossOrigin="anonymous"/>
        <link nonce="c59aa59a-aaa6-400a-943e-eea6a6df1e68" rel="preload" as="font" fetchPriority="high" href="//st.ozone.ru/s3/ozon-fonts/gt-eesti-pro-display-bold.woff2" type="font/woff2" crossOrigin="anonymous"/>
      </head>
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
